version: '3.8'

services:
  gun-relay:
    build:
      context: ./gun-relay
      dockerfile: Dockerfile
    container_name: gun-relay
    ports:
      - "8765:8765"
    volumes:
      - gun-data:/app/store
    environment:
      - GUN_RELAY_HOST=0.0.0.0
      - GUN_RELAY_PORT=8765
    networks:
      - free-association-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/gun"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  holster-relay:
    build:
      context: ./holster-relay
      dockerfile: Dockerfile
    container_name: holster-relay
    ports:
      - "8766:8766"
    volumes:
      - holster-data:/app/holster-data
    environment:
      - HOLSTER_RELAY_HOST=0.0.0.0
      - HOLSTER_RELAY_PORT=8766
      - HOLSTER_RELAY_STORAGE=true
      - HOLSTER_RELAY_STORAGE_PATH=./holster-data
    networks:
      - free-association-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8766/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  ai-proxy:
    build:
      context: ./ai-proxy
      dockerfile: Dockerfile
    container_name: ai-proxy
    ports:
      - "8767:8767"
    environment:
      - AI_PROXY_HOST=0.0.0.0
      - AI_PROXY_PORT=8767
      - NODE_ENV=${NODE_ENV:-development}
      - MASTER_API_KEY=${MASTER_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:5173,http://localhost:5174}
      - DEBUG=false
    networks:
      - free-association-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8767/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  gun-data:
    driver: local
  holster-data:
    driver: local

networks:
  free-association-network:
    driver: bridge
